import numpy as np

In [2]:
#Create an arrayof 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
#Create an array of 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
#Create an array of the integers from 10 to 50
np.arange(10,51,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [6]:
#Create an array of all the even integers from 10 to 50
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [10]:
#Create a 3x3 matrix with values ranging from 0 to 8
a=np.arange(9)
a=a.reshape([3,3])
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
#Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
#Use NumPy to generate a random number between 0 and 1
np.random.rand(1)

array([0.7996341])

In [13]:
#Use NumPy to generate a random number between 0 and 1
np.random.randn(25)

array([ 1.64000983, -0.20510472, -0.88767937,  0.52799784,  1.46265353,
        0.9398067 ,  0.07708932,  0.88049304, -1.40867978, -0.93773824,
        1.20063008,  0.3423354 ,  2.624178  , -1.16051078,  0.20555954,
        1.03415798, -2.43129859,  0.46153939, -0.52835178,  0.90299856,
        0.1351415 ,  0.5804116 , -1.7081188 , -3.10974651, -0.75276901])